[project]
name = "chatqwen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-ollama>=0.2.0",
    "streamlit>=1.40.1",
]
